spring:
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://localhost:5432/greenspace
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB

tokens:
  open-ai: Bearer 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
  plant-net: 2b10haQYlHDvRgsaSWOXNMWr1e